[project]
name = "python-uv"
version = "0.1.0"
description = "Add your description here"
requires-python = ">= 3.10"
dependencies = [
    "matplotlib",
    "numpy",
    "pyside6",
]

[tool.uv]
# Perfer system python (necesseray for NixOS)
python-preference = "system"
